# Generated by Django 4.1.2 on 2022-12-13 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet_list',
            name='owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projet_list',
            name='final_deadline',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
