# Generated by Django 4.1.2 on 2022-12-14 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projet_list_owner_alter_projet_list_final_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('start_of_project', models.DateField(default=django.utils.timezone.now, null=True)),
                ('final_deadline', models.DateField(default=django.utils.timezone.now, null=True)),
                ('deadlines', models.TextField(null=True)),
                ('team', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Projet_list',
        ),
    ]
