# Generated by Django 4.1.2 on 2022-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_list_delete_projet_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_list',
            name='deadlines_text',
            field=models.TextField(null=True),
        ),
    ]
