# Generated by Django 4.1.2 on 2022-12-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_list_deadlines_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_list',
            name='deadlines_name',
            field=models.TextField(null=True),
        ),
    ]
