# Generated by Django 4.1.2 on 2022-12-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='team',
            new_name='project',
        ),
    ]
