# Generated by Django 4.1.2 on 2022-12-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='media/')),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
