# Generated by Django 4.1.2 on 2022-12-13 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams_list',
            name='invited',
            field=models.TextField(null=True),
        ),
    ]
