# Generated by Django 4.1.2 on 2022-12-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teams_list_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams_list',
            name='projects',
            field=models.TextField(null=True),
        ),
    ]
