# Generated by Django 4.1.2 on 2022-12-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_acc',
            name='invited',
            field=models.TextField(null=True),
        ),
    ]
